# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('dataset_id', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ETLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('dataset_id', models.CharField(max_length=255)),
                ('view', models.CharField(max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('next_update', models.DateTimeField(null=True)),
                ('update_period', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(default='Sin Nombre', max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('state', models.CharField(default='A', max_length=2)),
                ('admin', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.Secretaries')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.Users'),
        ),
        migrations.AddField(
            model_name='etls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.Users'),
        ),
        migrations.AddField(
            model_name='datasets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.Users'),
        ),
    ]
